import type { Metadata } from "next";
import "./globals.css";
import TopBar from "@/components/top-bar";
import { UserProvider } from "@/lib/context/UserContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <TopBar />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
